<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
    <title>BCS STATISTICS REPORT</title>
    <meta name="description" content=""/>
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    @include('partials.header')

  </head>

  <body>

    {{ $slot }}

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="container">
            <p class="fs-compressed text-center">
              Program Development & Report Generated By: <span class="fw-bold">ICT SECTION, BPSC</span>. 
              <br>
              Report Generation Tag: {{ date('d-m-Y H:i:s'); }}
            </p>
          </div>
        </div>
      </div>
    </div>

    @include('partials.footer')

  </body>

</html>
