<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
    <title>BCS STATISTICS REPORT</title>
    <meta name="description" content=""/>
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    @include('partials.header')

  </head>

  <body>

    {{ $slot }}


      <div class="row">
        <div class="col-md-12">

            <p class="fs-compressed text-center mt-2">

              Software Developed & Report Generated By: <span class="fw-bold">ICT SECTION, BPSC</span>. 

              <br>

              @php date_default_timezone_set('Asia/Dhaka'); @endphp
              
              Report Generation Tag: {{ time() }} - {{ date('d-m-Y H:i:s') }} GMT{{ date('T') }}

            </p>

        </div>
      </div>


    @include('partials.footer-report')

  </body>

</html>
